services:
  db:
    container_name: db
    image: postgres:13
    volumes:
      - .database/potentiel-dev.dump:/dump/potentiel-dev.dump
      - .database/restore-dev-db.sh:/docker-entrypoint-initdb.d/restore-dev-db.sh
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db
    restart: always
    ports:
      - 5432:5432
